-- 在 Supabase 專案的 SQL Editor 貼上這整份，執行一次即可建立所需的資料表。
-- Dashboard 左側選單 -> SQL Editor -> New query -> 貼上 -> Run

create table if not exists writing_analyses (
  id bigint generated by default as identity primary key,
  task_type text,
  prompt_text text,
  essay_text text,
  band_score numeric,
  criteria jsonb,
  sentence_corrections jsonb,
  error_diagnosis jsonb,
  created_at timestamptz not null default now()
);

create table if not exists practice_attempts (
  id bigint generated by default as identity primary key,
  category text,
  subcategory text,
  question text,
  user_answer text,
  is_correct boolean,
  explanation_zh text,
  correct_answer text,
  created_at timestamptz not null default now()
);

-- 後端一律用 service_role key 連線（會繞過 RLS），前端不會直接連 Supabase，
-- 所以這裡不需要另外設定 Row Level Security policy。
