-- 在 Supabase 專案的 SQL Editor 貼上這整份，執行一次即可建立所需的資料表。
-- Dashboard 左側選單 -> SQL Editor -> New query -> 貼上 -> Run

create table if not exists writing_analyses (
  id bigint generated by default as identity primary key,
  task_type text,
  prompt_text text,
  essay_text text,
  band_score numeric,
  criteria jsonb,
  sentence_corrections jsonb,
  error_diagnosis jsonb,
  created_at timestamptz not null default now()
);

create table if not exists practice_attempts (
  id bigint generated by default as identity primary key,
  category text,
  subcategory text,
  question text,
  user_answer text,
  is_correct boolean,
  explanation_zh text,
  correct_answer text,
  created_at timestamptz not null default now()
);

-- 每個 category+subcategory 的學習狀態（難度階段、連對次數、題型/主題輪替記錄）
create table if not exists subcategory_state (
  id bigint generated by default as identity primary key,
  category text not null,
  subcategory text not null,
  difficulty_stage text not null default 'simple', -- simple | mixed | comprehensive
  streak int not null default 0,                   -- 目前連續答對次數（升階用）
  answered_count int not null default 0,           -- 已完成（答對過關）的題目數，每5題觸發⭐總結
  mastery_stars int,                               -- 最近一次⭐總結的星等（1-5）
  last_question_type text,                         -- 上一題題型（輪替用）
  recent_topics jsonb not null default '[]',       -- 最近用過的主題（輪替用）
  intro_shown_stages jsonb not null default '[]',  -- 已顯示過概念講解的階段
  updated_at timestamptz not null default now(),
  unique (category, subcategory)
);

-- practice_attempts 補欄位（既有資料庫請執行以下 alter）
alter table practice_attempts add column if not exists question_type text;
alter table practice_attempts add column if not exists topic text;
alter table practice_attempts add column if not exists retry_count int not null default 0;
alter table practice_attempts add column if not exists difficulty_stage text;
alter table practice_attempts add column if not exists corrections jsonb;

-- 後端一律用 service_role key 連線（會繞過 RLS），前端不會直接連 Supabase，
-- 所以這裡不需要另外設定 Row Level Security policy。
